#!/usr/bin/env python3
"""
EzUI Lua Bundler
Menggabungkan semua file Lua menjadi satu bundle file untuk Roblox
"""

import os
import re
from pathlib import Path

class LuaBundler:
    def __init__(self, root_dir):
        self.root_dir = Path(root_dir)
        self.processed_files = set()
        self.modules = {}

    def read_file(self, filepath):
        """Membaca file Lua"""
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                return f.read()
        except Exception as e:
            print(f"❌ Error membaca {filepath}: {e}")
            return None

    def resolve_path(self, require_path, current_file=None):
        """Resolve path dari require statement"""
        # Clean up the path
        require_path = require_path.strip('"').strip("'")

        # Handle relative paths
        if require_path.startswith("../"):
            if current_file:
                base_dir = Path(current_file).parent
                resolved = (base_dir / require_path).resolve()
            else:
                resolved = self.root_dir / require_path.replace("../", "")
        else:
            resolved = self.root_dir / require_path

        # Add .lua extension if not present
        if not resolved.suffix:
            resolved = resolved.with_suffix('.lua')

        return resolved

    def extract_requires(self, content):
        """Extract semua require statements dari konten"""
        # Pattern untuk menangkap require("path") atau require('path')
        pattern = r'require\s*\(\s*["\']([^"\']+)["\']\s*\)'
        return re.findall(pattern, content)

    def process_file(self, filepath, module_name=None):
        """Process single file dan dependencies-nya"""
        filepath = Path(filepath)

        # Avoid circular dependencies
        if str(filepath) in self.processed_files:
            return None

        self.processed_files.add(str(filepath))

        print(f"📄 Processing: {filepath.name}")

        content = self.read_file(filepath)
        if content is None:
            return None

        # Extract requires
        requires = self.extract_requires(content)

        # Process dependencies first
        for req in requires:
            dep_path = self.resolve_path(req, filepath)
            if dep_path.exists():
                self.process_file(dep_path, req)

        # Store module
        if module_name is None:
            module_name = str(filepath.relative_to(self.root_dir)).replace('.lua', '').replace(os.sep, '/')

        self.modules[module_name] = content

        return content

    def bundle(self, entry_file, output_file):
        """Bundle entry file dan semua dependencies-nya"""
        print(f"\n🚀 Starting bundler...")
        print(f"📁 Root: {self.root_dir}")
        print(f"📝 Entry: {entry_file}")
        print(f"💾 Output: {output_file}\n")

        # Reset state
        self.processed_files.clear()
        self.modules.clear()

        # Process entry file
        entry_path = self.root_dir / entry_file
        if not entry_path.exists():
            print(f"❌ Entry file tidak ditemukan: {entry_path}")
            return False

        main_content = self.process_file(entry_path)
        if main_content is None:
            return False

        # Build bundle
        bundle_content = self.build_bundle_content()

        # Write output
        output_path = self.root_dir / output_file
        output_path.parent.mkdir(parents=True, exist_ok=True)

        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(bundle_content)
            print(f"\n✅ Bundle berhasil dibuat: {output_path}")
            print(f"📊 Total modules: {len(self.modules)}")
            print(f"📏 Bundle size: {len(bundle_content)} characters")
            return True
        except Exception as e:
            print(f"❌ Error menulis output: {e}")
            return False

    def build_bundle_content(self):
        """Build konten bundle dari semua modules"""
        lines = []

        # Header
        lines.append("--[[")
        lines.append("    EzUI - Bundled Library")
        lines.append("    Auto-generated by EzUI Bundler")
        lines.append("    ")
        lines.append("    This file contains all EzUI modules bundled together.")
        lines.append("    Total modules: " + str(len(self.modules)))
        lines.append("]]")
        lines.append("")

        # Module loader system
        lines.append("-- Module Loader System")
        lines.append("local _MODULES = {}")
        lines.append("local _LOADED = {}")
        lines.append("")
        lines.append("local function require(moduleName)")
        lines.append("    if _LOADED[moduleName] then")
        lines.append("        return _LOADED[moduleName]")
        lines.append("    end")
        lines.append("    ")
        lines.append("    local moduleFunc = _MODULES[moduleName]")
        lines.append("    if not moduleFunc then")
        lines.append('        error("Module not found: " .. moduleName)')
        lines.append("    end")
        lines.append("    ")
        lines.append("    local result = moduleFunc()")
        lines.append("    _LOADED[moduleName] = result")
        lines.append("    return result")
        lines.append("end")
        lines.append("")

        # Register all modules
        lines.append("-- Register Modules")
        for module_name, content in self.modules.items():
            lines.append(f'_MODULES["{module_name}"] = function()')

            # Wrap module content
            # Remove comments at the beginning (optional)
            module_lines = content.split('\n')

            # Indent module content
            for line in module_lines:
                lines.append("    " + line)

            lines.append("end")
            lines.append("")

        # Entry point
        lines.append("-- Entry Point")
        lines.append("return require('main')")
        lines.append("")

        return '\n'.join(lines)


def create_executor_version(root):
    """Create executor-friendly standalone version"""
    print("\n[3/3] Creating Executor Version...")

    # Read bundle.lua (library)
    bundle_path = root / 'output' / 'bundle.lua'
    example_path = root / 'output' / 'example.lua'

    if not bundle_path.exists():
        print("❌ bundle.lua not found, run normal bundle first!")
        return False

    try:
        with open(bundle_path, 'r', encoding='utf-8') as f:
            bundle_content = f.read()

        # Remove the last line "return require('main')" from bundle
        bundle_lines = bundle_content.split('\n')
        # Find and remove the entry point line
        filtered_lines = [line for line in bundle_lines if not line.strip().startswith('return require')]
        bundle_without_return = '\n'.join(filtered_lines)

        # Create executor script
        executor_script = []
        executor_script.append("--[[")
        executor_script.append("    EzUI - Executor Ready Script")
        executor_script.append("    Auto-generated by EzUI Bundler")
        executor_script.append("    ")
        executor_script.append("    This script is ready to use with any Roblox executor!")
        executor_script.append("    Just paste and execute - GUI will appear automatically.")
        executor_script.append("    ")
        executor_script.append("    Features:")
        executor_script.append("    - Cyberpunk/Cyber theme with neon glow effects")
        executor_script.append("    - 4 example tabs (Home, Inputs, Settings, Notifications)")
        executor_script.append("    - All UI components demonstrated")
        executor_script.append("    - No external files needed - completely standalone!")
        executor_script.append("]]")
        executor_script.append("")
        executor_script.append("print('🚀 Loading EzUI Executor Script...')")
        executor_script.append("")

        # Add the bundle library code
        executor_script.append(bundle_without_return)
        executor_script.append("")

        # Add executor initialization code
        executor_script.append("-- Initialize EzUI Library")
        executor_script.append("local EzUI = require('main')")
        executor_script.append("")
        executor_script.append("print('✅ EzUI Library loaded!')")
        executor_script.append("print('🎮 Creating GUI...')")
        executor_script.append("")

        # Add example GUI code
        executor_script.append("-- Create Main Window")
        executor_script.append("local window = EzUI:CreateNew({")
        executor_script.append("    Name = 'EzUI Cyberpunk Demo',")
        executor_script.append("    Width = 750,")
        executor_script.append("    Height = 450,")
        executor_script.append("    Opacity = 0.95,")
        executor_script.append("    AutoAdapt = true,")
        executor_script.append("    AutoShow = true,")
        executor_script.append("    FolderName = 'EzUIExecutor',")
        executor_script.append("    FileName = 'ExecutorConfig'")
        executor_script.append("})")
        executor_script.append("")

        # Tab 1: Home
        executor_script.append("-- Tab 1: Home & Welcome")
        executor_script.append("local tabHome = window:AddTab('🏠 Home', 'rbxassetid://7733955511')")
        executor_script.append("tabHome:AddLabel('Welcome to EzUI Cyberpunk Theme! 🎮')")
        executor_script.append("tabHome:AddSeparator()")
        executor_script.append("tabHome:AddLabel('Executor-Ready Script - No external files needed!')")
        executor_script.append("")
        executor_script.append("tabHome:AddButton('Test Notification', function()")
        executor_script.append("    window:Notify({")
        executor_script.append("        Title = 'Success!',")
        executor_script.append("        Message = 'EzUI is working perfectly! ✨',")
        executor_script.append("        Type = 'success'")
        executor_script.append("    })")
        executor_script.append("end)")
        executor_script.append("")
        executor_script.append("tabHome:AddButton('Print to Console', function()")
        executor_script.append("    print('🎉 Button clicked from EzUI!')")
        executor_script.append("end)")
        executor_script.append("")

        # Tab 2: Inputs
        executor_script.append("-- Tab 2: Input Components")
        executor_script.append("local tabInputs = window:AddTab('📝 Inputs', 'rbxassetid://7733960981')")
        executor_script.append("tabInputs:AddLabel('Text & Number Inputs:')")
        executor_script.append("")
        executor_script.append("tabInputs:AddTextBox({")
        executor_script.append("    Title = 'Username',")
        executor_script.append("    Placeholder = 'Enter your username...',")
        executor_script.append("    DefaultValue = '',")
        executor_script.append("    Callback = function(value)")
        executor_script.append("        print('Username:', value)")
        executor_script.append("    end")
        executor_script.append("})")
        executor_script.append("")
        executor_script.append("tabInputs:AddNumberBox({")
        executor_script.append("    Title = 'Speed Multiplier',")
        executor_script.append("    DefaultValue = 1,")
        executor_script.append("    Min = 0.5,")
        executor_script.append("    Max = 5,")
        executor_script.append("    Step = 0.5,")
        executor_script.append("    Callback = function(value)")
        executor_script.append("        print('Speed set to:', value)")
        executor_script.append("    end")
        executor_script.append("})")
        executor_script.append("")

        # Tab 3: Settings
        executor_script.append("-- Tab 3: Toggles & Settings")
        executor_script.append("local tabSettings = window:AddTab('⚙️ Settings', 'rbxassetid://7733765398')")
        executor_script.append("tabSettings:AddLabel('Feature Toggles:')")
        executor_script.append("")
        executor_script.append("tabSettings:AddToggle({")
        executor_script.append("    Title = 'Enable Glow Effects',")
        executor_script.append("    DefaultValue = true,")
        executor_script.append("    Callback = function(enabled)")
        executor_script.append("        print('Glow effects:', enabled and 'ON' or 'OFF')")
        executor_script.append("    end")
        executor_script.append("})")
        executor_script.append("")
        executor_script.append("tabSettings:AddToggle({")
        executor_script.append("    Title = 'Auto Save Config',")
        executor_script.append("    DefaultValue = true,")
        executor_script.append("    Callback = function(enabled)")
        executor_script.append("        print('Auto save:', enabled and 'ON' or 'OFF')")
        executor_script.append("    end")
        executor_script.append("})")
        executor_script.append("")
        executor_script.append("tabSettings:AddSeparator()")
        executor_script.append("")
        executor_script.append("tabSettings:AddSelectBox({")
        executor_script.append("    Title = 'Theme Preset',")
        executor_script.append("    Options = {'Cyberpunk Cyan', 'Neon Purple', 'Electric Green', 'Hot Pink', 'Orange Neon'},")
        executor_script.append("    DefaultValue = 'Cyberpunk Cyan',")
        executor_script.append("    Callback = function(selected)")
        executor_script.append("        print('Theme:', selected)")
        executor_script.append("        window:Notify({")
        executor_script.append("            Title = 'Theme Updated',")
        executor_script.append("            Message = 'Selected: ' .. selected,")
        executor_script.append("            Type = 'info'")
        executor_script.append("        })")
        executor_script.append("    end")
        executor_script.append("})")
        executor_script.append("")

        # Tab 4: Notifications
        executor_script.append("-- Tab 4: Notification Tests")
        executor_script.append("local tabNotif = window:AddTab('🔔 Notifications', 'rbxassetid://7733993211')")
        executor_script.append("tabNotif:AddLabel('Test different notification types:')")
        executor_script.append("tabNotif:AddSeparator()")
        executor_script.append("")
        executor_script.append("tabNotif:AddButton('Success Notification', function()")
        executor_script.append("    window:Notify({Title = 'Success!', Message = 'Operation completed! ✅', Type = 'success'})")
        executor_script.append("end)")
        executor_script.append("")
        executor_script.append("tabNotif:AddButton('Warning Notification', function()")
        executor_script.append("    window:Notify({Title = 'Warning!', Message = 'Check your settings! ⚠️', Type = 'warning'})")
        executor_script.append("end)")
        executor_script.append("")
        executor_script.append("tabNotif:AddButton('Error Notification', function()")
        executor_script.append("    window:Notify({Title = 'Error!', Message = 'Something went wrong! ❌', Type = 'error'})")
        executor_script.append("end)")
        executor_script.append("")
        executor_script.append("tabNotif:AddButton('Info Notification', function()")
        executor_script.append("    window:Notify({Title = 'Info', Message = 'Informational message! ℹ️', Type = 'info'})")
        executor_script.append("end)")
        executor_script.append("")

        # Success notification
        executor_script.append("-- Show success message")
        executor_script.append("print('🎉 EzUI GUI created successfully!')")
        executor_script.append("print('📊 Stats:')")
        executor_script.append("print('  - 4 tabs created')")
        executor_script.append("print('  - Cyberpunk theme active')")
        executor_script.append("print('  - All components loaded!')")
        executor_script.append("")
        executor_script.append("window:Notify({")
        executor_script.append("    Title = 'Welcome! 🚀',")
        executor_script.append("    Message = 'EzUI Cyberpunk Theme is ready for executor!',")
        executor_script.append("    Type = 'success'")
        executor_script.append("})")
        executor_script.append("")
        executor_script.append("print('✅ Script execution completed!')")

        # Write executor version
        output_path = root / 'output' / 'executor.lua'
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(executor_script))

        print(f"✅ Executor version created: {output_path}")
        print(f"📊 Total lines: {len(executor_script)}")
        content_size = len('\n'.join(executor_script))
        print(f"📏 File size: {content_size} characters")

        return True

    except Exception as e:
        print(f"❌ Error creating executor version: {e}")
        return False


def main():
    """Main bundler function"""
    root = Path(__file__).parent
    bundler = LuaBundler(root)

    print("=" * 60)
    print("  EzUI Lua Bundler")
    print("=" * 60)

    # Bundle main library
    print("\n[1/3] Bundling Main Library...")
    success1 = bundler.bundle('main.lua', 'output/bundle.lua')

    # Bundle example
    print("\n[2/3] Bundling Example...")
    bundler2 = LuaBundler(root / 'example')
    success2 = bundler2.bundle('main.lua', '../output/example.lua')

    # Create executor version
    success3 = create_executor_version(root)

    print("\n" + "=" * 60)
    if success1 and success2 and success3:
        print("✅ Bundling selesai!")
        print("\nFiles generated:")
        print("  - output/bundle.lua (Main library - for Studio)")
        print("  - output/example.lua (Example code - for Studio)")
        print("  - output/executor.lua (Executor ready - standalone)")
    else:
        print("❌ Bundling gagal!")
    print("=" * 60)


if __name__ == "__main__":
    main()
